package model

import "slices"

var ItemNameMap = map[string]SaveFloat{
	"NOTHING":              -1,
	"POCKET KNIFE":         0,
	"KITCHEN KNIFE":        1,
	"COLA":                 2,
	"LEMONADE":             3,
	"COLA DELUXE":          4,
	"LEMONADE DELUXE":      5,
	"ZOOP":                 6,
	"ICE CREAM":            7,
	"MYSTERY POWDER":       8,
	"BUFF CHARM":           9,
	"FORTUNATE CHARM":      10,
	"STURDY CHARM":         11,
	"HASTY CHARM":          12,
	"CUTE CHARM":           13,
	"ATTRACTIVE CHARM":     14,
	"REASONABLE CHARM":     15,
	"FIRST AID KIT":        16,
	"EGG":                  17,
	"PACKED LUNCH":         18,
	"LEOTARD":              19,
	"ARCADE TOKEN":         20,
	"NET":                  21,
	"RED GEM":              22,
	"PINK GEM":             23,
	"BLUE GEM":             24,
	"GREEN GEM":            25,
	"STUDIO KEY":           26,
	"CHALICE KEY":          27,
	"BROOM":                28,
	"BATH BOMB":            29,
	"SNISSORS":             30,
	"BIG SCRIB":            31,
	"ROCK":                 32,
	"SPECIAL DELIVERY":     33,
	"CIGARETTE":            34,
	"EXTINGUISHER":         35,
	"CRUISE TICKET":        36,
	"TORCH":                37,
	"COOLROOM KEY":         38,
	"GRUMPY SNACK":         39,
	"PUFF SNACK":           40,
	"FUSSY SNACK":          41,
	"BUNKO BLADE":          42,
	"CRAM CUP":             43,
	"CRICKET BAT":          44,
	"LINT":                 45,
	"CHARRED ENCHILADA":    46,
	"ICED COFFEE":          47,
	"BRASS BELL":           48,
	"WITCH PAMPHLET":       49,
	"SPINNING TOP":         50,
	"BUG BUSTER":           51,
	"FRESH HERB":           52,
	"RED KEY":              53,
	"SOUP":                 54,
	"RAT CROWN":            55,
	"SIGNED PHOTO":         56,
	"RED CARD KEY":         57,
	"BLUE CARD KEY":        58,
	"GREEN CARD KEY":       59,
	"PINK CARD KEY":        60,
	"SPECIAL DELIVERY 2":   61,
	"KOMBUCHA":             62,
	"FLAT WHITE":           63,
	"LATTE":                64,
	"LONG BLACK":           65,
	"CAPPUCCINO":           66,
	"HOT CHOCOLATE":        67,
	"CRAMPPACCINO":         68,
	"ARCHIE'S MEMENTO":     69,
	"SOURDOUGH LOAF":       70,
	"EVERYTHING BAGEL":     71,
	"NOTHING BAGEL":        72,
	"ROSEMARY BAGEL":       73,
	"DARK RYE BAGEL":       74,
	"PLAIN BAGEL":          75,
	"BLUEBERRY BAGEL":      76,
	"HEALTH DRINK":         77,
	"CAMP KNIFE":           78,
	"FERAL OOZE":           79,
	"RUBBER GLOVES":        80,
	"HEADPHONES":           81,
	"TOUGH GLOVES":         82,
	"TINY TOKEN":           83,
	"PETTY KNIFE":          84,
	"MINUS PIN":            85,
	"PLUS PIN":             86,
	"EGG PIN":              87,
	"STAG PIN":             88,
	"SWORDFISH PIN":        89,
	"GARDEN PIN":           90,
	"SURF PIN":             91,
	"FROG PIN":             92,
	"SCOTT PIN":            93,
	"SNOW GLOVES":          94,
	"GAMESHOW PIN":         95,
	"FROACH PIN":           96,
	"PUPPY PIN":            97,
	"WHISPER PIN":          98,
	"ERROR PIN":            99,
	"CD-ROM.01":            100,
	"CD-ROM.02":            101,
	"CD-ROM.03":            102,
	"CD-ROM.04":            103,
	"CD-ROM.05":            104,
	"CD-ROM.06":            105,
	"CD-ROM.07":            106,
	"CD-ROM.08":            107,
	"WOODEN PALLET0":       108,
	"COOL MINERAL":         109,
	"GLOSSARY APP":         110,
	"LOOKER APP":           111,
	"WOODEN PALLET1":       112,
	"CURE ALL":             113,
	"ROCK CHARM":           114,
	"MEMBERSHIP CARD":      115,
	"EXP. BOOSTER":         116,
	"GREEN TEA":            117,
	"EARL GREY TEA":        118,
	"BREAKFAST TEA":        119,
	"PEPPERMINT TEA":       120,
	"STRAWBERRY MILK":      121,
	"BANANA MILK":          122,
	"LIME MILK":            123,
	"CHOCCY MILK":          124,
	"CORN CHIPS":           125,
	"SOUR LOLLIES":         126,
	"STINK BOMB":           127,
	"ZAPPER":               128,
	"WIND UP ROBOT":        129,
	"CHOCOLATE BAR":        130,
	"MINIMUM CHIPS":        131,
	"MAXIMUM CHIPS":        132,
	"POTATO CAKE":          133,
	"POTATO SCALLOP":       134,
	"ERROR KNIFE":          135,
	"APPLE":                136,
	"PEACH":                137,
	"GRAPES":               138,
	"PEAR":                 139,
	"BANANA":               140,
	"POCKET PUPPY":         141,
	"DOG BISCUIT":          142,
	"FISHING BAIT":         143,
	"OLD BOOT":             144,
	"OLD CAN":              145,
	"ORBFISH":              146,
	"BRATFISH":             147,
	"EGGFISH":              148,
	"SASSFISH":             149,
	"BLANDFISH":            150,
	"DINKOFISH":            151,
	"ENERGY TONIC":         152,
	"POWER TONIC":          153,
	"ODD BRACER":           154,
	"ILL BRACER":           155,
	"BIG BISCUIT":          156,
	"ANDY'S ENCOURAGEMENT": 157,
	"SLUDGE BUSTER":        158,
	"GOLDEN STAGE":         159,
	"RARE GORDON":          160,
	"HEALTH ORB":           161,
	"EFFORT ORB":           162,
	"SPOOF MASK":           163,
	"RAMUE":                164,
	"ERROR CROWN":          165,
	"MEAN CHIPS":           166,
	"BUG CROWN":            167,
	"BAD BISCUIT":          168,
}

var ItemIDMap map[SaveFloat]string
var ItemNameList []string

func init() {
	ItemNameList = make([]string, 0, len(ItemNameMap))
	ItemIDMap = make(map[SaveFloat]string, len(ItemNameMap))
	for n := range ItemNameMap {
		ItemNameList = append(ItemNameList, n)
		ItemIDMap[ItemNameMap[n]] = n
	}
	slices.Sort(ItemNameList)
}
