package model

var ItemNameID = map[string]float64{
	"nothing":              -1,
	"pocket knife":         0,
	"kitchen knife":        1,
	"cola":                 2,
	"lemonade":             3,
	"cola deluxe":          4,
	"lemonade deluxe":      5,
	"zoop":                 6,
	"ice cream":            7,
	"mystery powder":       8,
	"buff charm":           9,
	"fortunate charm":      10,
	"sturdy charm":         11,
	"hasty charm":          12,
	"cute charm":           13,
	"attractive charm":     14,
	"reasonable charm":     15,
	"first aid kit":        16,
	"egg":                  17,
	"packed lunch":         18,
	"leotard":              19,
	"arcade token":         20,
	"net":                  21,
	"red gem":              22,
	"pink gem":             23,
	"blue gem":             24,
	"green gem":            25,
	"studio key":           26,
	"chalice key":          27,
	"broom":                28,
	"bath bomb":            29,
	"snissors":             30,
	"big scrib":            31,
	"rock":                 32,
	"special delivery":     33,
	"cigarette":            34,
	"extinguisher":         35,
	"cruise ticket":        36,
	"torch":                37,
	"coolroom key":         38,
	"grumpy snack":         39,
	"puff snack":           40,
	"fussy snack":          41,
	"bunko blade":          42,
	"cram cup":             43,
	"cricket bat":          44,
	"lint":                 45,
	"charred enchilada":    46,
	"iced coffee":          47,
	"brass bell":           48,
	"witch pamphlet":       49,
	"spinning top":         50,
	"bug buster":           51,
	"fresh herb":           52,
	"red key":              53,
	"soup":                 54,
	"rat crown":            55,
	"signed photo":         56,
	"red card key":         57,
	"blue card key":        58,
	"green card key":       59,
	"pink card key":        60,
	"special delivery 2":   61,
	"kombucha":             62,
	"flat white":           63,
	"latte":                64,
	"long black":           65,
	"cappuccino":           66,
	"hot chocolate":        67,
	"cramppaccino":         68,
	"archie's memento":     69,
	"sourdough loaf":       70,
	"everything bagel":     71,
	"nothing bagel":        72,
	"rosemary bagel":       73,
	"dark rye bagel":       74,
	"plain bagel":          75,
	"blueberry bagel":      76,
	"health drink":         77,
	"camp knife":           78,
	"feral ooze":           79,
	"rubber gloves":        80,
	"headphones":           81,
	"tough gloves":         82,
	"tiny token":           83,
	"petty knife":          84,
	"minus pin":            85,
	"plus pin":             86,
	"egg pin":              87,
	"stag pin":             88,
	"swordfish pin":        89,
	"garden pin":           90,
	"surf pin":             91,
	"frog pin":             92,
	"scott pin":            93,
	"snow gloves":          94,
	"gameshow pin":         95,
	"froach pin":           96,
	"puppy pin":            97,
	"whisper pin":          98,
	"error pin":            99,
	"cd-rom.01":            100,
	"cd-rom.02":            101,
	"cd-rom.03":            102,
	"cd-rom.04":            103,
	"cd-rom.05":            104,
	"cd-rom.06":            105,
	"cd-rom.07":            106,
	"cd-rom.08":            107,
	"wooden pallet0":       108,
	"cool mineral":         109,
	"glossary app":         110,
	"looker app":           111,
	"wooden pallet1":       112,
	"cure all":             113,
	"rock charm":           114,
	"membership card":      115,
	"exp. booster":         116,
	"green tea":            117,
	"earl grey tea":        118,
	"breakfast tea":        119,
	"peppermint tea":       120,
	"strawberry milk":      121,
	"banana milk":          122,
	"lime milk":            123,
	"choccy milk":          124,
	"odd bracer":           154,
	"ill bracer":           155,
	"big biscuit":          156,
	"andy's encouragement": 157,
	"sludge buster":        158,
	"golden stage":         159,
	"rare gordon":          160,
	"health orb":           161,
	"effort orb":           162,
	"spoof mask":           163,
	"ramue":                164,
	"error crown":          165,
	"mean chips":           166,
	"bug crown":            167,
	"bad biscuit":          168,
}
